<?php

namespace App\Console\Commands;

use App\Support\CatalogueSeed;
use Illuminate\Console\Command;

class ExportDatabase extends Command
{
    protected $signature = 'db:export-setup';

    protected $description = 'Generate supabase/setup.sql for the SQL Editor without contacting the database';

    public function handle(CatalogueSeed $seed): int
    {
        $sql = "-- Generated by php artisan db:export-setup. Do not edit.\nBEGIN;\nSELECT pg_advisory_xact_lock(23092026);\n";
        $sql .= file_get_contents(database_path('schema/supabase.sql'))."\n";
        $sql .= file_get_contents(database_path('schema/query-indexes.sql'))."\n";
        $sql .= file_get_contents(database_path('schema/community.sql'))."\n";
        $sql .= file_get_contents(database_path('schema/social.sql'))."\n";
        $sql .= file_get_contents(database_path('schema/submissions.sql'))."\n";
        $sql .= file_get_contents(database_path('schema/enrichment.sql'))."\n";
        $sql .= file_get_contents(database_path('schema/listing.sql'))."\n";
        $sql .= file_get_contents(database_path('schema/review-photos.sql'))."\n";
        $sql .= file_get_contents(database_path('schema/recovery.sql'))."\n";
        $sql .= $seed->sql()."\nCOMMIT;\n";
        file_put_contents(base_path('supabase/setup.sql'), $sql);
        $this->info('Generated supabase/setup.sql. No remote changes were made.');

        return self::SUCCESS;
    }
}
