-- Catalogue enrichment stores our own source data and Google Place IDs only.
ALTER TABLE public.mt_places ADD COLUMN IF NOT EXISTS opening_periods jsonb;
ALTER TABLE public.mt_places ADD COLUMN IF NOT EXISTS hours_updated_at timestamptz;
ALTER TABLE public.mt_places ADD COLUMN IF NOT EXISTS hours_source text;
ALTER TABLE public.mt_places ADD COLUMN IF NOT EXISTS google_place_id text;

CREATE TABLE IF NOT EXISTS public.mt_source_settings (
  place_id bigint PRIMARY KEY REFERENCES public.mt_places(id) ON DELETE CASCADE,
  url text NOT NULL CHECK (url LIKE 'https://%' AND length(url) <= 2000),
  enabled boolean NOT NULL DEFAULT true,
  checked_at timestamptz,
  next_check_at timestamptz NOT NULL DEFAULT now(),
  candidate_photo jsonb,
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS mt_sources_due ON public.mt_source_settings(next_check_at) WHERE enabled;
CREATE TABLE IF NOT EXISTS public.mt_source_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  place_id bigint NOT NULL REFERENCES public.mt_places(id) ON DELETE CASCADE,
  status text NOT NULL CHECK (status IN ('updated','unchanged','robots_denied','unavailable','no_match','photo_approved')),
  hours_updated boolean NOT NULL DEFAULT false,
  photo_found boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS mt_source_logs_place ON public.mt_source_logs(place_id,created_at DESC);
CREATE TABLE IF NOT EXISTS public.mt_google_matches (
  place_id bigint PRIMARY KEY REFERENCES public.mt_places(id) ON DELETE CASCADE,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','matched','review','unmatched','error','excluded')),
  candidate_ids jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(candidate_ids)='array'),
  checked_at timestamptz,
  next_check_at timestamptz NOT NULL DEFAULT now(),
  attempts integer NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS mt_google_matches_due ON public.mt_google_matches(next_check_at) WHERE status IN ('pending','error');
-- These records contain private moderation state, not a public Google content cache.
ALTER TABLE public.mt_source_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mt_source_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mt_google_matches ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.mt_source_settings,public.mt_source_logs,public.mt_google_matches FROM anon,authenticated;
GRANT SELECT ON public.mt_source_settings,public.mt_source_logs,public.mt_google_matches TO authenticated;
GRANT ALL ON public.mt_source_settings,public.mt_source_logs,public.mt_google_matches TO service_role;
GRANT USAGE,SELECT ON SEQUENCE public.mt_source_logs_id_seq TO service_role;
DROP POLICY IF EXISTS mt_source_settings_admin ON public.mt_source_settings;
CREATE POLICY mt_source_settings_admin ON public.mt_source_settings FOR SELECT TO authenticated USING ((SELECT public.mt_is_admin()));
DROP POLICY IF EXISTS mt_source_logs_admin ON public.mt_source_logs;
CREATE POLICY mt_source_logs_admin ON public.mt_source_logs FOR SELECT TO authenticated USING ((SELECT public.mt_is_admin()));
DROP POLICY IF EXISTS mt_google_matches_admin ON public.mt_google_matches;
CREATE POLICY mt_google_matches_admin ON public.mt_google_matches FOR SELECT TO authenticated USING ((SELECT public.mt_is_admin()));

CREATE OR REPLACE FUNCTION public.mt_apply_source_hours(target_place bigint, periods jsonb, source_url text) RETURNS void
LANGUAGE plpgsql SECURITY INVOKER SET search_path = '' AS $$
BEGIN
  IF jsonb_typeof(periods) <> 'array' OR jsonb_array_length(periods) NOT BETWEEN 1 AND 28 OR EXISTS (
    SELECT 1 FROM jsonb_array_elements(periods) p WHERE (p->>'day')::int NOT BETWEEN 0 AND 6
      OR (p->>'opens')::int NOT BETWEEN 0 AND 1439 OR (p->>'closes')::int NOT BETWEEN 1 AND 1440
      OR (p->>'opens')::int >= (p->>'closes')::int
      OR NOT (p ? 'day' AND p ? 'opens' AND p ? 'closes')
  ) THEN RAISE EXCEPTION 'Invalid source hours' USING ERRCODE='23514'; END IF;
  UPDATE public.mt_places SET opening_periods=periods, hours_source=source_url,hours_updated_at=now() WHERE id=target_place;
END;
$$;
REVOKE ALL ON FUNCTION public.mt_apply_source_hours(bigint,jsonb,text) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.mt_apply_source_hours(bigint,jsonb,text) TO service_role;

CREATE TABLE IF NOT EXISTS public.mt_enrichment_usage (
  day date PRIMARY KEY DEFAULT current_date,
  google_requests integer NOT NULL DEFAULT 0
);
ALTER TABLE public.mt_enrichment_usage ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.mt_enrichment_usage FROM anon,authenticated;
GRANT ALL ON public.mt_enrichment_usage TO service_role;
CREATE OR REPLACE FUNCTION public.mt_claim_google_request(daily_limit integer) RETURNS boolean
LANGUAGE plpgsql SECURITY INVOKER SET search_path='' AS $$
DECLARE consumed integer;
BEGIN
  IF daily_limit NOT BETWEEN 1 AND 100 THEN RETURN false; END IF;
  INSERT INTO public.mt_enrichment_usage(day,google_requests) VALUES(current_date,1)
    ON CONFLICT(day) DO UPDATE SET google_requests=public.mt_enrichment_usage.google_requests+1
    WHERE public.mt_enrichment_usage.google_requests<daily_limit RETURNING google_requests INTO consumed;
  DELETE FROM public.mt_enrichment_usage WHERE day<current_date-90;
  RETURN consumed IS NOT NULL;
END; $$;
CREATE OR REPLACE FUNCTION public.mt_queue_google_matches() RETURNS void
LANGUAGE sql SECURITY INVOKER SET search_path='' AS $$
  INSERT INTO public.mt_google_matches(place_id) SELECT id FROM public.mt_places WHERE published AND google_place_id IS NULL ON CONFLICT DO NOTHING;
$$;
REVOKE ALL ON FUNCTION public.mt_claim_google_request(integer),public.mt_queue_google_matches() FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.mt_claim_google_request(integer),public.mt_queue_google_matches() TO service_role;

-- First-party daily ranking: no Google scores or derived Google ranking is stored.
CREATE TABLE IF NOT EXISTS public.mt_daily_picks (
  place_id bigint PRIMARY KEY REFERENCES public.mt_places(id) ON DELETE CASCADE,
  position smallint NOT NULL UNIQUE CHECK(position BETWEEN 1 AND 5),
  computed_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.mt_daily_picks ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.mt_daily_picks FROM anon,authenticated;
GRANT SELECT ON public.mt_daily_picks TO anon,authenticated;
GRANT ALL ON public.mt_daily_picks TO service_role;
DROP POLICY IF EXISTS mt_daily_picks_public ON public.mt_daily_picks;
CREATE POLICY mt_daily_picks_public ON public.mt_daily_picks FOR SELECT TO anon,authenticated USING (EXISTS(SELECT 1 FROM public.mt_places p WHERE p.id=place_id AND p.published AND p.access<>'restricted' AND p.community_count>=3));
CREATE OR REPLACE FUNCTION public.mt_refresh_daily_picks() RETURNS void
LANGUAGE plpgsql SECURITY INVOKER SET search_path='' AS $$
BEGIN
  PERFORM pg_advisory_xact_lock(29092026);
  DELETE FROM public.mt_daily_picks;
  INSERT INTO public.mt_daily_picks(place_id,position)
    SELECT id,row_number() OVER(ORDER BY community_rating DESC,community_count DESC,id)::smallint
    FROM public.mt_places WHERE published AND access<>'restricted' AND community_count>=3
    ORDER BY community_rating DESC,community_count DESC,id LIMIT 5;
END; $$;
REVOKE ALL ON FUNCTION public.mt_refresh_daily_picks() FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.mt_refresh_daily_picks() TO service_role;
