-- Listing status and facts extracted from cited sources. Nothing is ever deleted: a place that is
-- no longer open to visitors is archived (hidden) with its reason and evidence, and can be restored.
ALTER TABLE public.mt_places ADD COLUMN IF NOT EXISTS details jsonb NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE public.mt_places ADD COLUMN IF NOT EXISTS listing_status text NOT NULL DEFAULT 'active';
ALTER TABLE public.mt_places ADD COLUMN IF NOT EXISTS archived boolean NOT NULL DEFAULT false;
ALTER TABLE public.mt_places ADD COLUMN IF NOT EXISTS status_checked_at timestamptz;

DO $constraints$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'mt_places_details_object') THEN
    ALTER TABLE public.mt_places ADD CONSTRAINT mt_places_details_object
      CHECK (jsonb_typeof(details) = 'object' AND pg_column_size(details) <= 16000);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'mt_places_listing_status') THEN
    ALTER TABLE public.mt_places ADD CONSTRAINT mt_places_listing_status
      CHECK (listing_status IN ('active','needs_review','closed'));
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'mt_places_archived_hidden') THEN
    ALTER TABLE public.mt_places ADD CONSTRAINT mt_places_archived_hidden CHECK (NOT (archived AND published));
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'mt_places_closed_archived') THEN
    ALTER TABLE public.mt_places ADD CONSTRAINT mt_places_closed_archived CHECK (listing_status <> 'closed' OR archived);
  END IF;
END
$constraints$;

-- Every status change keeps its reason and evidence. Only administrators can read it.
CREATE TABLE IF NOT EXISTS public.mt_listing_audits (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  place_id bigint NOT NULL REFERENCES public.mt_places(id) ON DELETE CASCADE,
  from_status text NOT NULL CHECK (from_status IN ('active','needs_review','closed')),
  to_status text NOT NULL CHECK (to_status IN ('active','needs_review','closed')),
  reason text NOT NULL CHECK (char_length(reason) BETWEEN 1 AND 1000),
  evidence_url text CHECK (evidence_url IS NULL OR (evidence_url LIKE 'https://%' AND char_length(evidence_url) <= 2000)),
  checked_on date NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS mt_listing_audits_place ON public.mt_listing_audits(place_id, created_at DESC);
ALTER TABLE public.mt_listing_audits ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.mt_listing_audits FROM anon, authenticated;
GRANT SELECT ON public.mt_listing_audits TO authenticated;
GRANT ALL ON public.mt_listing_audits TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.mt_listing_audits_id_seq TO service_role;
DROP POLICY IF EXISTS mt_listing_audits_admin ON public.mt_listing_audits;
CREATE POLICY mt_listing_audits_admin ON public.mt_listing_audits FOR SELECT TO authenticated USING ((SELECT public.mt_is_admin()));

-- One transaction per change: status, visibility and the audit row cannot drift apart.
-- Closing archives and hides the place. Reopening restores only what this function hid, so an
-- editorial draft (unpublished, never archived) stays a draft.
CREATE OR REPLACE FUNCTION public.mt_set_listing_status(target_place bigint, new_status text, why text, evidence text, checked date) RETURNS void
LANGUAGE plpgsql SECURITY INVOKER SET search_path = '' AS $$
DECLARE previous text;
BEGIN
  IF new_status NOT IN ('active','needs_review','closed') THEN RAISE EXCEPTION 'Invalid listing status' USING ERRCODE = '22023'; END IF;
  SELECT listing_status INTO previous FROM public.mt_places WHERE id = target_place FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Place not found' USING ERRCODE = '23503'; END IF;
  IF new_status = 'closed' THEN
    UPDATE public.mt_places SET listing_status = 'closed', archived = true, published = false, status_checked_at = now() WHERE id = target_place;
  ELSE
    UPDATE public.mt_places SET listing_status = new_status, published = CASE WHEN archived THEN true ELSE published END, archived = false, status_checked_at = now() WHERE id = target_place;
  END IF;
  INSERT INTO public.mt_listing_audits(place_id, from_status, to_status, reason, evidence_url, checked_on)
    VALUES (target_place, previous, new_status, why, evidence, checked);
END;
$$;
REVOKE ALL ON FUNCTION public.mt_set_listing_status(bigint, text, text, text, date) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mt_set_listing_status(bigint, text, text, text, date) TO service_role;
