-- Run in a Supabase project, inside the transaction generated by npm run db:prepare.
-- Namespaced mt_* tables leave other applications' tables untouched.
CREATE TABLE IF NOT EXISTS public.mt_metadata (key text PRIMARY KEY, value text NOT NULL);
CREATE TABLE IF NOT EXISTS public.mt_profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  role text NOT NULL DEFAULT 'user' CHECK (role IN ('user','admin'))
);
CREATE OR REPLACE FUNCTION public.mt_create_profile() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
BEGIN
  INSERT INTO public.mt_profiles(id) VALUES (NEW.id) ON CONFLICT DO NOTHING;
  RETURN NEW;
END;
$$;
REVOKE ALL ON FUNCTION public.mt_create_profile() FROM PUBLIC;
DROP TRIGGER IF EXISTS mt_profile_created ON auth.users;
CREATE TRIGGER mt_profile_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.mt_create_profile();
INSERT INTO public.mt_profiles(id) SELECT id FROM auth.users ON CONFLICT DO NOTHING;
CREATE OR REPLACE FUNCTION public.mt_is_admin() RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = '' AS $$
  SELECT EXISTS (SELECT 1 FROM public.mt_profiles WHERE id = (SELECT auth.uid()) AND role = 'admin');
$$;
REVOKE ALL ON FUNCTION public.mt_is_admin() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.mt_is_admin() TO anon, authenticated;
CREATE TABLE IF NOT EXISTS public.mt_places (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL CHECK (char_length(name) BETWEEN 1 AND 160),
  type text NOT NULL CHECK (type IN ('restaurant','activity')),
  lat double precision NOT NULL CHECK (lat BETWEEN -90 AND 90),
  lng double precision NOT NULL CHECK (lng BETWEEN -180 AND 180),
  location text NOT NULL CHECK (char_length(location) BETWEEN 1 AND 160),
  description text NOT NULL CHECK (char_length(description) BETWEEN 1 AND 3000),
  description_fr text CHECK (char_length(description_fr) <= 3000),
  rating double precision CHECK (rating BETWEEN 0 AND 5),
  hours text CHECK (char_length(hours) <= 200),
  tags jsonb NOT NULL DEFAULT '[]' CHECK (jsonb_typeof(tags) = 'array' AND jsonb_array_length(tags) <= 20),
  image text CHECK (image IS NULL OR image LIKE 'https://%' OR image LIKE '/photos/%'),
  photo_credit jsonb,
  sources jsonb NOT NULL DEFAULT '[]' CHECK (jsonb_typeof(sources) = 'array'),
  access text NOT NULL DEFAULT 'unknown' CHECK (access IN ('unknown','open','restricted')),
  published boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.mt_saved_places (
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  place_id bigint NOT NULL REFERENCES public.mt_places(id) ON DELETE CASCADE,
  kind text NOT NULL CHECK (kind IN ('favorites','revisits')),
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY(user_id,place_id,kind)
);
CREATE INDEX IF NOT EXISTS mt_saved_places_place_idx ON public.mt_saved_places(place_id);
CREATE TABLE IF NOT EXISTS public.mt_rate_limits (
  key text PRIMARY KEY,
  hits integer NOT NULL,
  expires_at timestamptz NOT NULL
);
CREATE OR REPLACE FUNCTION public.mt_check_rate_limit(identifier text, ceiling integer) RETURNS boolean
LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
DECLARE current_hits integer;
BEGIN
  IF identifier !~ '^[a-f0-9]{64}$' OR ceiling < 1 OR ceiling > 100 THEN RAISE EXCEPTION 'Invalid rate limit'; END IF;
  DELETE FROM public.mt_rate_limits WHERE expires_at < now();
  INSERT INTO public.mt_rate_limits(key,hits,expires_at) VALUES(identifier,1,now()+interval '15 minutes')
  ON CONFLICT(key) DO UPDATE SET hits = public.mt_rate_limits.hits + 1
  RETURNING hits INTO current_hits;
  RETURN current_hits <= ceiling;
END;
$$;
REVOKE ALL ON FUNCTION public.mt_check_rate_limit(text,integer) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mt_check_rate_limit(text,integer) TO service_role;

ALTER TABLE public.mt_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mt_places ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mt_saved_places ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mt_metadata ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mt_rate_limits ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.mt_profiles, public.mt_places, public.mt_saved_places, public.mt_metadata, public.mt_rate_limits FROM anon, authenticated;
GRANT SELECT ON public.mt_places, public.mt_metadata TO anon, authenticated;
GRANT SELECT ON public.mt_profiles TO authenticated;
GRANT INSERT, UPDATE, DELETE ON public.mt_places TO authenticated;
GRANT SELECT, INSERT, DELETE ON public.mt_saved_places TO authenticated;
GRANT USAGE ON SEQUENCE public.mt_places_id_seq TO authenticated;
GRANT ALL ON public.mt_profiles, public.mt_places, public.mt_saved_places, public.mt_metadata, public.mt_rate_limits TO service_role;
GRANT USAGE ON SEQUENCE public.mt_places_id_seq TO service_role;
DROP POLICY IF EXISTS mt_own_profile ON public.mt_profiles;
CREATE POLICY mt_own_profile ON public.mt_profiles FOR SELECT TO authenticated USING (id = (SELECT auth.uid()));
DROP POLICY IF EXISTS mt_read_places ON public.mt_places;
CREATE POLICY mt_read_places ON public.mt_places FOR SELECT TO anon, authenticated USING (published OR (SELECT public.mt_is_admin()));
DROP POLICY IF EXISTS mt_admin_insert ON public.mt_places;
CREATE POLICY mt_admin_insert ON public.mt_places FOR INSERT TO authenticated WITH CHECK ((SELECT public.mt_is_admin()));
DROP POLICY IF EXISTS mt_admin_update ON public.mt_places;
CREATE POLICY mt_admin_update ON public.mt_places FOR UPDATE TO authenticated USING ((SELECT public.mt_is_admin())) WITH CHECK ((SELECT public.mt_is_admin()));
DROP POLICY IF EXISTS mt_admin_delete ON public.mt_places;
CREATE POLICY mt_admin_delete ON public.mt_places FOR DELETE TO authenticated USING ((SELECT public.mt_is_admin()));
DROP POLICY IF EXISTS mt_read_saved ON public.mt_saved_places;
CREATE POLICY mt_read_saved ON public.mt_saved_places FOR SELECT TO authenticated USING (user_id = (SELECT auth.uid()));
DROP POLICY IF EXISTS mt_insert_saved ON public.mt_saved_places;
CREATE POLICY mt_insert_saved ON public.mt_saved_places FOR INSERT TO authenticated WITH CHECK (user_id = (SELECT auth.uid()) AND EXISTS (SELECT 1 FROM public.mt_places WHERE id = place_id AND published));
DROP POLICY IF EXISTS mt_delete_saved ON public.mt_saved_places;
CREATE POLICY mt_delete_saved ON public.mt_saved_places FOR DELETE TO authenticated USING (user_id = (SELECT auth.uid()));
DROP POLICY IF EXISTS mt_public_version ON public.mt_metadata;
CREATE POLICY mt_public_version ON public.mt_metadata FOR SELECT TO anon, authenticated USING (key = 'schema_version');
INSERT INTO public.mt_metadata(key,value) VALUES ('schema_version','1') ON CONFLICT DO NOTHING;
